server:
  port: 8761

eureka:
  client:
    # 下面两行代码的意思：只把Eureka当成Eureka Server，不把它当成Eureka Client。
    # 因为只是单机使用，不需要进行多个Eureka Server操作
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
      # defaultZone: http://root:123456@localhost:8761/eureka

# 进Eureka Server主页加认证，需要spring boot security依赖
#spring:
#  security:
#    user:
#      name: root
#      password: 123456